version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/entity_research
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads
      - ./instance:/app/instance

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=entity_research
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
